name: Build and Test

on:
#  push:
#    branches:
#      - development
#      - main
  pull_request:
    branches:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 22
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

#      - name: Run Tests
#        run: mvn test