name: Sync Development with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout Development branch
        run: |
          git fetch origin
          git checkout development

      - name: Rebase Development with Main
        run: |
          git rebase origin/main  

      - name: Push rebased Development branch
        run: |
          git push --force-with-lease origin development  
